plugins {
    id 'java-library'
    id 'kotlin'
}
// maven 插件在 Gradle 7.x 中已废弃，暂时注释
// apply plugin: 'maven'
apply from:"../maven_publish.gradle"

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

compileKotlin {
    kotlinOptions {
        jvmTarget = "11"
    }
}

compileTestKotlin {
    kotlinOptions {
        jvmTarget = "11"
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

group 'com.anymore'
version VERSION
